# Generated by Django 5.2.5 on 2025-08-14 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="titre")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "date_debut",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date de début"
                    ),
                ),
                ("date_fin", models.DateTimeField(verbose_name="date de fin")),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["date_debut"],
            },
        ),
    ]
