# Generated by Django 5.2.5 on 2025-08-14 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="auteur",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["ADMIN", "PROFESSOR"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evenements_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
