# Generated by Django 5.2.5 on 2025-08-14 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Annonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="titre")),
                ("contenu", models.TextField(verbose_name="contenu")),
                (
                    "audience",
                    models.CharField(
                        choices=[("PUBLIC", "Publique"), ("INTERNE", "Interne")],
                        default="INTERNE",
                        max_length=10,
                        verbose_name="audience",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de création",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "verbose_name_plural": "Annonces",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sujet", models.CharField(max_length=150, verbose_name="sujet")),
                ("corps", models.TextField(verbose_name="corps")),
                (
                    "date_envoi",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date d'envoi"
                    ),
                ),
                (
                    "lu_le",
                    models.DateTimeField(blank=True, null=True, verbose_name="lu le"),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-date_envoi"],
            },
        ),
    ]
