# Generated by Django 5.2.5 on 2025-08-14 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="montant total"
                    ),
                ),
                (
                    "date_emission",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="date d'émission",
                    ),
                ),
                ("date_echeance", models.DateField(verbose_name="date d'échéance")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("ENVOYEE", "Envoyée"),
                            ("PAYEE", "Payée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="BROUILLON",
                        max_length=10,
                        verbose_name="statut",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-date_emission"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="montant"
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date de paiement",
                    ),
                ),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("CARTE", "Carte de crédit"),
                            ("VIREMENT", "Virement bancaire"),
                            ("ESPECES", "Espèces"),
                        ],
                        max_length=10,
                        verbose_name="méthode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement"],
            },
        ),
    ]
