# Generated by Django 5.2.5 on 2025-08-14 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="eleve",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="facture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="administration.facture",
            ),
        ),
    ]
