# Generated by Django 5.2.5 on 2025-08-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "justifiee",
                    models.BooleanField(default=False, verbose_name="justifiée"),
                ),
                ("motif", models.TextField(blank=True, verbose_name="motif")),
            ],
            options={
                "verbose_name": "Absence",
                "verbose_name_plural": "Absences",
            },
        ),
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, verbose_name="nom")),
            ],
            options={
                "verbose_name": "Classe",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.CreateModel(
            name="EmploiDuTemps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("LUNDI", "Lundi"),
                            ("MARDI", "Mardi"),
                            ("MERCREDI", "Mercredi"),
                            ("JEUDI", "Jeudi"),
                            ("VENDREDI", "Vendredi"),
                            ("SAMEDI", "Samedi"),
                        ],
                        max_length=10,
                        verbose_name="jour",
                    ),
                ),
                ("heure_debut", models.TimeField(verbose_name="heure de début")),
                ("heure_fin", models.TimeField(verbose_name="heure de fin")),
            ],
            options={
                "verbose_name": "Emploi du temps",
                "verbose_name_plural": "Emplois du temps",
                "ordering": ["jour", "heure_debut"],
            },
        ),
        migrations.CreateModel(
            name="Evaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="titre")),
                ("date", models.DateField(verbose_name="date")),
            ],
            options={
                "verbose_name": "Évaluation",
                "verbose_name_plural": "Évaluations",
            },
        ),
        migrations.CreateModel(
            name="Matiere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
            ],
            options={
                "verbose_name": "Matière",
                "verbose_name_plural": "Matières",
            },
        ),
        migrations.CreateModel(
            name="Niveau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=50, unique=True, verbose_name="nom"),
                ),
            ],
            options={
                "verbose_name": "Niveau",
                "verbose_name_plural": "Niveaux",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="note"
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(blank=True, verbose_name="commentaire"),
                ),
            ],
            options={
                "verbose_name": "Note",
                "verbose_name_plural": "Notes",
            },
        ),
    ]
