# Generated by Django 5.2.5 on 2025-08-14 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="eleve",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="eleves",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "STUDENT"},
                related_name="classes_enrolled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="professeurs",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "PROFESSOR"},
                related_name="classes_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emploi_du_temps",
                to="academics.classe",
            ),
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="professeur",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cours_timetable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="absence",
            name="cours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="absences",
                to="academics.emploidutemps",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="classe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="academics.classe",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="professeur",
            field=models.ForeignKey(
                limit_choices_to={"role": "PROFESSOR"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="matiere",
            name="professeurs",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "PROFESSOR"},
                related_name="matieres_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="academics.matiere",
            ),
        ),
        migrations.AddField(
            model_name="emploidutemps",
            name="matiere",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="academics.matiere"
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="niveau",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.niveau",
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="eleve",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="evaluation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="academics.evaluation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classe",
            unique_together={("nom", "niveau")},
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("eleve", "evaluation")},
        ),
    ]
